#!/bin/bash

sort -u */*.pub | ssh "$@" tee -a '~/.ssh/authorized_keys.new'
ssh "$@" cp '~/.ssh/authorized_keys' '~/.ssh/authorized_keys.old'
ssh "$@" chmod 644 '~/.ssh/authorized_keys.new'
ssh "$@" mv '~/.ssh/authorized_keys.new' '~/.ssh/authorized_keys'
ssh "$@" echo "Keys installed successfully"

