#!/bin/bash

set -e

ssh() {
	/usr/bin/ssh \
			-oControlMaster=auto \
			-oControlPersist=yes \
			-oControlPath=/tmp/%r@%h.sock \
			-oStrictHostKeyChecking=no \
			-oUserKnownHostsFile=/dev/null \
			"$@"
}

ssh "$@" mkdir -m700 '~/.ssh' || true
sort -u */*.pub | ssh "$@" tee -a '~/.ssh/authorized_keys.new' >/dev/null
ssh "$@" cp '~/.ssh/authorized_keys' '~/.ssh/authorized_keys.old' || true
ssh "$@" chmod 644 '~/.ssh/authorized_keys.new'
ssh "$@" mv '~/.ssh/authorized_keys.new' '~/.ssh/authorized_keys'
ssh "$@" echo "Keys installed successfully"

